from app.tools.variable import *

# ==================================================
# 默认设置列表
# ==================================================
DEFAULT_SETTINGS = {
    "window": {
        "width": {"default_value": 800},
        "height": {"default_value": 600},
        "is_maximized": {"default_value": False},
        "pre_maximized_width": {"default_value": 800},
        "pre_maximized_height": {"default_value": 600},
    },
    "settings": {
        "width": {"default_value": 800},
        "height": {"default_value": 600},
        "is_maximized": {"default_value": False},
        "pre_maximized_width": {"default_value": 800},
        "pre_maximized_height": {"default_value": 600},
    },
    "float_position": {
        "height": {"default_value": "screen_height_half"},
        "width": {"default_value": "screen_width_half"},
        "x": {"default_value": 100},
        "y": {"default_value": 100},
    },
    "basic_settings": {
        "autostart": {"default_value": False},
        "show_startup_window": {"default_value": True},
        "main_window_topmost_mode": {"default_value": 0},
        "background_resident": {"default_value": True},
        "auto_save_window_size": {"default_value": True},
        "url_protocol": {"default_value": False},
        "dpiScale": {"default_value": "Auto"},
        "font": {"default_value": DEFAULT_FONT_NAME_PRIMARY},
        "font_weight": {"default_value": "3"},
        "theme": {"default_value": "AUTO"},
        "theme_color": {"default_value": DEFAULT_THEME_COLOR},
        "language": {"default_value": "ZH_CN"},
        "guide_completed": {"default_value": False},
    },
    "backup": {
        "auto_backup_enabled": {"default_value": True},
        "auto_backup_interval_days": {"default_value": 7},
        "auto_backup_max_count": {"default_value": 16},
        "include_config": {"default_value": True},
        "include_list": {"default_value": True},
        "include_language": {"default_value": False},
        "include_history": {"default_value": True},
        "include_audio": {"default_value": False},
        "include_cses": {"default_value": True},
        "include_images": {"default_value": True},
        "include_themes": {"default_value": True},
        "include_logs": {"default_value": False},
    },
    "roll_call_list": {
        "select_class_name": {"default_value": ""},
    },
    "roll_call_table": {
        "select_class_name": {"default_value": 0},
    },
    "lottery_list": {
        "select_pool_name": {"default_value": 0},
    },
    "lottery_table": {
        "select_pool_name": {"default_value": 0},
    },
    "roll_call_settings": {
        "draw_mode": {"default_value": 1},
        "clear_record": {"default_value": 0},
        "half_repeat": {"default_value": 1},
        "draw_type": {"default_value": 0},
        "default_class": {"default_value": ""},
        "font_size": {"default_value": 50},
        "display_format": {"default_value": 0},
        "display_style": {"default_value": 0},
        "use_global_font": {"default_value": 0},
        "custom_font": {"default_value": DEFAULT_FONT_NAME_PRIMARY},
        "show_random": {"default_value": 0},
        "animation": {"default_value": 1},
        "animation_interval": {"default_value": 80},
        "autoplay_count": {"default_value": 5},
        "result_flow_animation_style": {"default_value": False},
        "result_flow_animation_duration": {"default_value": 250},
        "animation_color_theme": {"default_value": 0},
        "animation_fixed_color": {"default_value": DEFAULT_THEME_COLOR},
        "student_image": {"default_value": False},
        "student_image_position": {"default_value": 0},
        "animation_music": {"default_value": ""},
        "result_music": {"default_value": ""},
        "animation_music_volume": {"default_value": 100},
        "result_music_volume": {"default_value": 100},
        "animation_music_fade_in": {"default_value": 300},
        "result_music_fade_in": {"default_value": 300},
        "animation_music_fade_out": {"default_value": 300},
        "result_music_fade_out": {"default_value": 300},
    },
    "quick_draw_settings": {
        "draw_mode": {"default_value": 1},
        "half_repeat": {"default_value": 1},
        "draw_type": {"default_value": 0},
        "default_class": {"default_value": ""},
        "disable_after_click": {"default_value": 1},
        "draw_count": {"default_value": 1},
        "font_size": {"default_value": 50},
        "display_format": {"default_value": 0},
        "use_global_font": {"default_value": 0},
        "custom_font": {"default_value": DEFAULT_FONT_NAME_PRIMARY},
        "show_random": {"default_value": 0},
        "animation": {"default_value": 1},
        "animation_interval": {"default_value": 80},
        "autoplay_count": {"default_value": 5},
        "animation_color_theme": {"default_value": 0},
        "result_color_theme": {"default_value": 0},
        "animation_fixed_color": {"default_value": DEFAULT_THEME_COLOR},
        "student_image": {"default_value": False},
        "student_image_position": {"default_value": 0},
        "animation_music": {"default_value": ""},
        "result_music": {"default_value": ""},
        "animation_music_volume": {"default_value": 100},
        "result_music_volume": {"default_value": 100},
        "animation_music_fade_in": {"default_value": 300},
        "result_music_fade_in": {"default_value": 300},
        "animation_music_fade_out": {"default_value": 300},
        "result_music_fade_out": {"default_value": 300},
    },
    "lottery_settings": {
        "draw_mode": {"default_value": 1},
        "clear_record": {"default_value": 0},
        "half_repeat": {"default_value": 1},
        "default_pool": {"default_value": ""},
        "font_size": {"default_value": 50},
        "display_format": {"default_value": 0},
        "display_style": {"default_value": 0},
        "use_global_font": {"default_value": 0},
        "custom_font": {"default_value": DEFAULT_FONT_NAME_PRIMARY},
        "show_random": {"default_value": 0},
        "animation": {"default_value": 1},
        "animation_interval": {"default_value": 80},
        "autoplay_count": {"default_value": 5},
        "result_flow_animation_style": {"default_value": False},
        "result_flow_animation_duration": {"default_value": 250},
        "animation_color_theme": {"default_value": 0},
        "result_color_theme": {"default_value": 0},
        "animation_fixed_color": {"default_value": DEFAULT_THEME_COLOR},
        "lottery_image": {"default_value": False},
        "lottery_image_position": {"default_value": 0},
        "animation_music": {"default_value": ""},
        "result_music": {"default_value": ""},
        "animation_music_volume": {"default_value": 100},
        "result_music_volume": {"default_value": 100},
        "animation_music_fade_in": {"default_value": 300},
        "result_music_fade_in": {"default_value": 300},
        "animation_music_fade_out": {"default_value": 300},
        "result_music_fade_out": {"default_value": 300},
    },
    "face_detector_settings": {
        "detector_type": {"default_value": ""},
        "picker_frame_color": {"default_value": DEFAULT_THEME_COLOR},
        "play_process_audio": {"default_value": True},
        "play_result_audio": {"default_value": True},
        "picking_duration_seconds": {"default_value": 2},
    },
    "roll_call_notification_settings": {
        "call_notification_service": {"default_value": False},
        "animation": {"default_value": True},
        "auto_close_time": {"default_value": 5},
        "enabled_monitor": {"default_value": "OFF"},
        "window_position": {"default_value": 0},
        "horizontal_offset": {"default_value": 0},
        "vertical_offset": {"default_value": 0},
        "transparency": {"default_value": 0.8},
        "floating_window_enabled_monitor": {"default_value": "OFF"},
        "floating_window_position": {"default_value": 0},
        "floating_window_horizontal_offset": {"default_value": 0},
        "floating_window_vertical_offset": {"default_value": 0},
        "floating_window_transparency": {"default_value": 0.8},
        "floating_window_auto_close_time": {"default_value": 5},
        "use_main_window_when_exceed_threshold": {"default_value": True},
        "main_window_display_threshold": {"default_value": 5},
        "notification_service_type": {"default_value": 0},
        "notification_display_duration": {"default_value": 5},
    },
    "quick_draw_notification_settings": {
        "call_notification_service": {"default_value": True},
        "animation": {"default_value": True},
        "auto_close_time": {"default_value": 5},
        "enabled_monitor": {"default_value": "OFF"},
        "window_position": {"default_value": 0},
        "horizontal_offset": {"default_value": 0},
        "vertical_offset": {"default_value": 0},
        "transparency": {"default_value": 0.8},
        "floating_window_enabled_monitor": {"default_value": "OFF"},
        "floating_window_position": {"default_value": 0},
        "floating_window_horizontal_offset": {"default_value": 0},
        "floating_window_vertical_offset": {"default_value": 0},
        "floating_window_transparency": {"default_value": 0.8},
        "floating_window_auto_close_time": {"default_value": 5},
        "notification_service_type": {"default_value": 0},
        "notification_display_duration": {"default_value": 5},
    },
    "lottery_notification_settings": {
        "call_notification_service": {"default_value": False},
        "animation": {"default_value": True},
        "auto_close_time": {"default_value": 5},
        "enabled_monitor": {"default_value": "OFF"},
        "window_position": {"default_value": 0},
        "horizontal_offset": {"default_value": 0},
        "vertical_offset": {"default_value": 0},
        "transparency": {"default_value": 0.8},
        "floating_window_enabled_monitor": {"default_value": "OFF"},
        "floating_window_position": {"default_value": 0},
        "floating_window_horizontal_offset": {"default_value": 0},
        "floating_window_vertical_offset": {"default_value": 0},
        "floating_window_transparency": {"default_value": 0.8},
        "floating_window_auto_close_time": {"default_value": 5},
        "use_main_window_when_exceed_threshold": {"default_value": True},
        "main_window_display_threshold": {"default_value": 5},
        "notification_service_type": {"default_value": 0},
        "notification_display_duration": {"default_value": 5},
    },
    "basic_safety_settings": {
        "verification_process": {"default_value": 0},
        "safety_switch": {"default_value": False},
        "totp_switch": {"default_value": False},
        "usb_switch": {"default_value": False},
        "show_hide_floating_window_switch": {"default_value": False},
        "restart_switch": {"default_value": False},
        "exit_switch": {"default_value": False},
        "open_settings_switch": {"default_value": False},
        "preview_settings_switch": {"default_value": False},
    },
    "page_management": {
        "roll_call_method": {"default_value": 1},
        "roll_call_reset_button": {"default_value": True},
        "roll_call_quantity_control": {"default_value": True},
        "roll_call_start_button": {"default_value": True},
        "roll_call_list": {"default_value": True},
        "roll_call_range": {"default_value": True},
        "roll_call_gender": {"default_value": True},
        "roll_call_remaining_button": {"default_value": True},
        "roll_call_quantity_label": {"default_value": 0},
        "lottery_method": {"default_value": 1},
        "lottery_reset_button": {"default_value": True},
        "lottery_quantity_control": {"default_value": True},
        "lottery_start_button": {"default_value": True},
        "lottery_list": {"default_value": True},
        "lottery_roll_call_list": {"default_value": True},
        "lottery_roll_call_range": {"default_value": True},
        "lottery_roll_call_gender": {"default_value": True},
        "lottery_remaining_button": {"default_value": True},
        "lottery_quantity_label": {"default_value": 0},
    },
    "floating_window_management": {
        "startup_display_floating_window": {"default_value": True},
        "floating_window_opacity": {"default_value": 0.8},
        "floating_window_topmost_mode": {"default_value": 1},
        "extend_quick_draw_component": {"default_value": False},
        "floating_window_button_control": {"default_value": 3},
        "floating_window_placement": {"default_value": 1},
        "floating_window_display_style": {"default_value": 0},
        "floating_window_theme": {"default_value": 0},
        "floating_window_stick_to_edge": {"default_value": True},
        "floating_window_stick_to_edge_recover_seconds": {"default_value": 3},
        "floating_window_long_press_duration": {"default_value": 500},
        "floating_window_stick_to_edge_display_style": {"default_value": 1},
        "floating_window_draggable": {"default_value": True},
        "floating_window_size": {"default_value": 3},
        "do_not_steal_focus": {"default_value": True},
        "hide_floating_window_on_foreground": {"default_value": False},
        "hide_floating_window_on_foreground_window_titles": {"default_value": ""},
        "hide_floating_window_on_foreground_process_names": {"default_value": ""},
    },
    "sidebar_management_window": {
        "roll_call_sidebar_position": {"default_value": 1},
        "lottery_sidebar_position": {"default_value": 1},
        "camera_preview_sidebar_position": {"default_value": 1},
        "main_window_history": {"default_value": 1},
        "settings_icon": {"default_value": 1},
    },
    "tray_management": {
        "show_hide_main_window": {"default_value": True},
        "open_settings": {"default_value": True},
        "show_hide_float_window": {"default_value": True},
        "restart": {"default_value": True},
        "exit": {"default_value": True},
    },
    "basic_voice_settings": {
        "voice_enable": {"default_value": False},
        "voice_engine": {"default_value": 0},
        "edge_tts_voice_name": {"default_value": "zh-CN-XiaoxiaoNeural"},
        "volume_size": {"default_value": 80},
        "speech_rate": {"default_value": 100},
        "system_volume_control": {"default_value": False},
        "system_volume_size": {"default_value": 50},
    },
    "specific_announcements": {
        "enabled": {"default_value": True},
        "default_mode": {"default_value": 0},
        "roll_call_fields": {
            "default_value": {"id": True, "name": True, "prefix": "", "suffix": ""}
        },
        "lottery_fields": {
            "default_value": {"id": True, "name": True, "prefix": "", "suffix": ""}
        },
    },
    "theme_management": {
        "roll_call_theme_id": {"default_value": ""},
        "lottery_theme_id": {"default_value": ""},
        "roll_call_theme_type": {"default_value": ""},
        "lottery_theme_type": {"default_value": ""},
    },
    "background_management": {
        "main_window_background_mode": {"default_value": 0},
        "main_window_background_color": {"default_value": "#ffd9d2"},
        "main_window_background_gradient_start": {"default_value": "#ffd9d2"},
        "main_window_background_gradient_end": {"default_value": "#d2fffb"},
        "main_window_background_gradient_direction": {"default_value": 0},
        "main_window_background_gradient_direction_v2": {"default_value": True},
        "main_window_background_image": {"default_value": ""},
        "main_window_background_brightness": {"default_value": 10},
        "main_window_background_blur_enable": {"default_value": False},
        "main_window_background_blur_radius": {"default_value": 15},
        "settings_window_background_mode": {"default_value": 0},
        "settings_window_background_color": {"default_value": "#ffd9d2"},
        "settings_window_background_gradient_start": {"default_value": "#ffd9d2"},
        "settings_window_background_gradient_end": {"default_value": "#d2fffb"},
        "settings_window_background_gradient_direction": {"default_value": 0},
        "settings_window_background_gradient_direction_v2": {"default_value": True},
        "settings_window_background_image": {"default_value": ""},
        "settings_window_background_brightness": {"default_value": 10},
        "settings_window_background_blur_enable": {"default_value": False},
        "settings_window_background_blur_radius": {"default_value": 15},
        "notification_floating_window_background_mode": {"default_value": 0},
        "notification_floating_window_background_color": {"default_value": "#ffd9d2"},
        "notification_floating_window_background_gradient_start": {
            "default_value": "#ffd9d2"
        },
        "notification_floating_window_background_gradient_end": {
            "default_value": "#d2fffb"
        },
        "notification_floating_window_background_gradient_direction": {
            "default_value": 0
        },
        "notification_floating_window_background_gradient_direction_v2": {
            "default_value": True
        },
        "notification_floating_window_background_image": {"default_value": ""},
        "notification_floating_window_background_brightness": {"default_value": 10},
        "notification_floating_window_background_blur_enable": {"default_value": False},
        "notification_floating_window_background_blur_radius": {"default_value": 15},
    },
    "history_management": {
        "show_roll_call_history": {"default_value": True},
        "select_class_name": {"default_value": 0},
        "select_weight": {"default_value": False},
        "show_lottery_history": {"default_value": True},
        "select_pool_name": {"default_value": 0},
    },
    "roll_call_history_table": {
        "select_class_name": {"default_value": 0},
    },
    "lottery_history_table": {
        "select_pool_name": {"default_value": 0},
    },
    "linkage_settings": {
        "verification_required": {"default_value": True},
        "instant_draw_disable": {"default_value": False},
        "data_source": {"default_value": 0},
        "hide_floating_window_on_class_end": {"default_value": False},
        "pre_class_reset_enabled": {"default_value": False},
        "pre_class_reset_time": {"default_value": 120},
        "pre_class_enable_time": {"default_value": 0},
        "post_class_disable_delay": {"default_value": 0},
        "subject_history_filter_enabled": {"default_value": False},
        "subject_history_break_assignment": {"default_value": 1},
    },
    "fair_draw_settings": {
        "fair_draw": {"default_value": True},
        "fair_draw_group": {"default_value": True},
        "fair_draw_gender": {"default_value": True},
        "fair_draw_time": {"default_value": False},
        "base_weight": {"default_value": 1.00},
        "min_weight": {"default_value": 0.50},
        "max_weight": {"default_value": 5.00},
        "frequency_function": {"default_value": 1},
        "frequency_weight": {"default_value": 1.00},
        "group_weight": {"default_value": 0.80},
        "gender_weight": {"default_value": 0.80},
        "time_weight": {"default_value": 0.50},
        "cold_start_enabled": {"default_value": True},
        "cold_start_rounds": {"default_value": 10},
        "shield_enabled": {"default_value": False},
        "shield_time": {"default_value": 5.00},
        "shield_time_unit": {"default_value": 0},
        "enable_avg_gap_protection": {"default_value": False},
        "gap_threshold": {"default_value": 1},
        "min_pool_size": {"default_value": 5},
    },
    "update": {
        "auto_update_mode": {"default_value": 3},
        "update_channel": {"default_value": 0},
        "update_source": {"default_value": 0},
        "last_check_time": {"default_value": "1970-01-01 08:00:00"},
    },
    "shortcut_settings": {
        "enable_shortcut": {"default_value": False},
        "open_roll_call_page": {"default_value": ""},
        "use_quick_draw": {"default_value": ""},
        "open_lottery_page": {"default_value": ""},
        "increase_roll_call_count": {"default_value": ""},
        "decrease_roll_call_count": {"default_value": ""},
        "increase_lottery_count": {"default_value": ""},
        "decrease_lottery_count": {"default_value": ""},
        "start_roll_call": {"default_value": ""},
        "start_lottery": {"default_value": ""},
    },
    "user_info": {
        "first_use_time": {"default_value": ""},
        "total_runtime_seconds": {"default_value": 0},
        "total_draw_count": {"default_value": 0},
        "roll_call_total_count": {"default_value": 0},
        "lottery_total_count": {"default_value": 0},
    },
}
